name: Hello World
on:
  pull_request:
    types: [opened]
jobs:
  startup:
    name: run startup script
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
  build:
    name: Here is my build task
    runs-on: ubuntu-latest
    needs: startup
    steps:
      - name: comment on PR
        run: gh pr comment $PR_URL --body "Thanks for your PR.We will review shortly"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
      - name: checkout code
        uses: actions/checkout@2
        with:
          fetch-depth: 0
      - name: check for buttons
        run: ./.github/scripts/checker.sh
        env:
          FILE: ./src/components/Buttons.js